<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-AU4DUGCC" failures="1" tests="1" name="Default test" time="64.513" errors="0" timestamp="2023-09-14T23:04:42 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="60.982">
    <failure type="java.lang.AssertionError" message="expected [Account Number: 486171182] but found [Account Number: 486171185]">
      <![CDATA[java.lang.AssertionError: expected [Account Number: 486171182] but found [Account Number: 486171185]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.dBankdemo.Testscripts.WithdrawMoney.the_user_should_verify(WithdrawMoney.java:65)
at âœ½.the User should Verify-"Account Number: 486171182"(file:///C:/Users/Hello/eclipse-workspace/RllDigitalBank/Feature/withdraw_money_from_account.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
